"""
AI Training Job Simulator
=========================
Simulates an ML training workload (like BERT fine-tuning or ResNet training).
Exposes training metrics to Prometheus:
  - Loss curve (exponentially decreasing with noise)
  - Accuracy (increasing)
  - Throughput (samples/sec)
  - Step count
  - Epoch progress
  - CPU/memory load via numpy matrix multiplication

Exposes: http://localhost:8001/metrics
"""

import os
import time
import math
import random
import threading
import numpy as np
from prometheus_client import (
    start_http_server, Gauge, Counter, Summary,
    REGISTRY, PROCESS_COLLECTOR, PLATFORM_COLLECTOR
)

REGISTRY.unregister(PROCESS_COLLECTOR)
REGISTRY.unregister(PLATFORM_COLLECTOR)

# ── Config ────────────────────────────────────────────────────────────────────
JOB_NAME = os.environ.get("JOB_NAME", "bert-finetuning")
TOTAL_EPOCHS = int(os.environ.get("EPOCHS", 100))
STEPS_PER_EPOCH = 200
STEP_DURATION = 0.5   # seconds per training step

# ── Prometheus Metrics ────────────────────────────────────────────────────────
training_loss = Gauge(
    'training_loss',
    'Current training loss',
    ['job_name', 'phase']
)

training_accuracy = Gauge(
    'training_accuracy_percent',
    'Current training accuracy (%)',
    ['job_name', 'phase']
)

training_step_total = Counter(
    'training_step_total',
    'Total training steps completed',
    ['job_name']
)

training_epoch = Gauge(
    'training_epoch',
    'Current training epoch',
    ['job_name']
)

training_throughput = Gauge(
    'training_throughput_samples_per_sec',
    'Training throughput in samples/second',
    ['job_name']
)

training_learning_rate = Gauge(
    'training_learning_rate',
    'Current learning rate',
    ['job_name']
)

training_gradient_norm = Gauge(
    'training_gradient_norm',
    'Gradient L2 norm',
    ['job_name']
)

training_batch_size = Gauge(
    'training_batch_size',
    'Batch size used for training',
    ['job_name']
)

cpu_load_percent = Gauge(
    'training_cpu_load_percent',
    'CPU load generated by training workload',
    ['job_name']
)

memory_used_bytes = Gauge(
    'training_memory_used_bytes',
    'Memory used by training process',
    ['job_name']
)

job_status = Gauge(
    'training_job_active',
    '1 if job is running, 0 if stopped',
    ['job_name']
)


# ── Learning Rate Scheduler ────────────────────────────────────────────────────

def cosine_lr(step: int, total_steps: int, base_lr=3e-4, min_lr=1e-6) -> float:
    """Cosine annealing schedule with warmup."""
    warmup_steps = total_steps // 10
    if step < warmup_steps:
        return base_lr * (step / warmup_steps)
    progress = (step - warmup_steps) / (total_steps - warmup_steps)
    return min_lr + 0.5 * (base_lr - min_lr) * (1 + math.cos(math.pi * progress))


# ── Simulated Loss Curve ──────────────────────────────────────────────────────

def compute_loss(step: int, total_steps: int) -> float:
    """Realistic loss: exponential decay + noise + occasional spikes."""
    base = 2.5 * math.exp(-3.5 * step / total_steps) + 0.05
    noise = random.gauss(0, 0.02)
    # Occasional gradient explosion spike (5% chance)
    spike = random.gauss(0, 0.3) if random.random() < 0.05 else 0
    return max(0.01, base + noise + spike)


def compute_accuracy(step: int, total_steps: int) -> float:
    """Accuracy: sigmoid-like growth."""
    base = 100 / (1 + math.exp(-8 * (step / total_steps - 0.4)))
    noise = random.gauss(0, 0.3)
    return min(99.9, max(0, base + noise))


# ── CPU Load Generator ────────────────────────────────────────────────────────

_cpu_load_value = 0.0
_cpu_lock = threading.Lock()

def cpu_stress_worker():
    """Burns CPU via matrix multiplication (simulates actual training compute)."""
    global _cpu_load_value
    size = int(os.environ.get("MATRIX_SIZE", 256))
    while True:
        t0 = time.perf_counter()
        a = np.random.randn(size, size).astype(np.float32)
        b = np.random.randn(size, size).astype(np.float32)
        np.dot(a, b)
        elapsed = time.perf_counter() - t0

        # Estimate CPU load (rough: how much time was compute vs sleep)
        with _cpu_lock:
            _cpu_load_value = min(100, elapsed * 1000 * random.uniform(0.8, 1.2))

        time.sleep(STEP_DURATION * 0.3)


# ── Training Loop ─────────────────────────────────────────────────────────────

def training_loop():
    total_steps = TOTAL_EPOCHS * STEPS_PER_EPOCH
    step = 0
    batch_size = 32

    job_status.labels(JOB_NAME).set(1)
    training_batch_size.labels(JOB_NAME).set(batch_size)

    print(f"[Training Simulator] Job: {JOB_NAME}")
    print(f"[Training Simulator] Epochs: {TOTAL_EPOCHS} | Steps/epoch: {STEPS_PER_EPOCH}")

    for epoch in range(1, TOTAL_EPOCHS + 1):
        training_epoch.labels(JOB_NAME).set(epoch)

        for local_step in range(STEPS_PER_EPOCH):
            step += 1
            t0 = time.time()

            loss = compute_loss(step, total_steps)
            acc = compute_accuracy(step, total_steps)
            lr = cosine_lr(step, total_steps)
            grad_norm = random.uniform(0.5, 2.5) * (1 - step / total_steps * 0.5)
            throughput = batch_size / STEP_DURATION * random.uniform(0.9, 1.1)

            # Update metrics
            training_loss.labels(JOB_NAME, "train").set(loss)
            training_accuracy.labels(JOB_NAME, "train").set(acc)
            training_step_total.labels(JOB_NAME).inc()
            training_learning_rate.labels(JOB_NAME).set(lr)
            training_gradient_norm.labels(JOB_NAME).set(grad_norm)
            training_throughput.labels(JOB_NAME).set(throughput)

            with _cpu_lock:
                cpu_load_percent.labels(JOB_NAME).set(_cpu_load_value)

            # Memory grows slightly over training (like a real job)
            mem_gb = 2.0 + (step / total_steps) * 4.0 + random.gauss(0, 0.1)
            memory_used_bytes.labels(JOB_NAME).set(max(0, mem_gb * 1024**3))

            elapsed = time.time() - t0
            sleep_time = max(0, STEP_DURATION - elapsed)
            time.sleep(sleep_time)

        # Validation at end of epoch
        val_loss = compute_loss(step, total_steps) * random.uniform(1.0, 1.15)
        val_acc = compute_accuracy(step, total_steps) * random.uniform(0.97, 1.0)
        training_loss.labels(JOB_NAME, "val").set(val_loss)
        training_accuracy.labels(JOB_NAME, "val").set(val_acc)

        if epoch % 10 == 0:
            print(f"[Epoch {epoch:3d}/{TOTAL_EPOCHS}] loss={loss:.4f} acc={acc:.2f}% lr={lr:.2e}")

    # Training complete
    job_status.labels(JOB_NAME).set(0)
    print(f"[Training Simulator] Job complete after {total_steps} steps.")

    # Restart after 30 seconds (continuous demo loop)
    time.sleep(30)
    training_loop()


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8001))
    print(f"[Training Simulator] Starting on port {port}")
    print(f"[Training Simulator] Metrics: http://localhost:{port}/metrics")

    start_http_server(port)

    # Start CPU stress worker
    t1 = threading.Thread(target=cpu_stress_worker, daemon=True)
    t1.start()

    # Start training loop in background
    t2 = threading.Thread(target=training_loop, daemon=True)
    t2.start()

    while True:
        time.sleep(60)
